development:
  server: directory.northwestern.edu
  port: 389
  treebase: "ou=People,dc=northwestern,dc=edu"

test:
  server: directory.northwestern.edu
  port: 389
  treebase: ou=People,dc=northwestern,dc=edu

cucumber:
  server: directory.northwestern.edu
  port: 389
  treebase: ou=People,dc=northwestern,dc=edu

production:
  server: 
  port: 
  treebase: 